$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1475201498853.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"46551dd2d62046ab86b529a2c7895fb1",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"02e594a5cb8e46848360667a5ad5302e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"db990852ebc84abf82832ff2cb120105"},
{
          "id":"0418d3d12fed4d1e89501050544353e7",
          "label":"item2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":211,
              "y":41},
            "size":{
              "width":221,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba47ac95f9234461800a2bfbcd3cc908",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":211,
                  "y":41},
                "size":{
                  "width":221,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["0418d3d12fed4d1e89501050544353e7"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/item2_u21.png",
            "selected~":"images/page_1/item2_u21.png"}},
{
          "id":"f22fa59de9124552b25335a4fb854f41",
          "label":"item3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":432,
              "y":41},
            "size":{
              "width":221,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40644d3cdcb34e7eaa2e04d7e3dd28bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":432,
                  "y":41},
                "size":{
                  "width":221,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["f22fa59de9124552b25335a4fb854f41"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/item2_u21.png",
            "selected~":"images/page_1/item2_u21.png"}},
{
          "id":"09f465a745ff4c4c97ef252a37d6a9cf",
          "label":"item5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":873,
              "y":41},
            "size":{
              "width":221,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e27408f07ec4a7d8a904d292207f21e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":873,
                  "y":41},
                "size":{
                  "width":221,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["09f465a745ff4c4c97ef252a37d6a9cf"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/item2_u21.png",
            "selected~":"images/page_1/item2_u21.png"}},
{
          "id":"e19057d1febe4f61a7cf94c46b043ca2",
          "label":"item4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":652,
              "y":41},
            "size":{
              "width":221,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe399e91dc6a4ae3903c262a380f90a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":652,
                  "y":41},
                "size":{
                  "width":221,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["e19057d1febe4f61a7cf94c46b043ca2"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/item2_u21.png",
            "selected~":"images/page_1/item2_u21.png"}},
{
          "id":"85cfb5be25464ab79890ab257b3cd47d",
          "label":"neirong",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":81},
            "size":{
              "width":1200,
              "height":310}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"cdb0f38b86fc4a5e9c8180376989f251",
              "label":"item1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0ffaba7204d8438880111befad12e664",
                  "label":"",
                  "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1200,
                      "height":310},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"293856866c194b30ab8de9f4b0887ffb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1200,
                          "height":310},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_1/u30.png"}},
{
                  "id":"dac9d943d26146879ec76622b722c223",
                  "label":"使用说明",
                  "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":214},
                    "size":{
                      "width":620,
                      "height":96}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c88e983b329d4acf93a98a99c5fa763c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":214},
                        "size":{
                          "width":620,
                          "height":96}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"a6330323971b46858246c61e5bf93dce",
              "label":"item2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"32a2a2f7e3f34e8484074b911ca73d50",
                  "label":"",
                  "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":310},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f0d3d0d9da7427396f54d8e22856629",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":310},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_1/u34.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"5129f842f54041ed97cab0912cfb0ccb",
              "label":"item3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6192acda93764b29b791150fccc08e5a",
                  "label":"",
                  "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                  "panelIndex":2,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":310},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7edb88f027904639b7f80bfed05cecd0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":310},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_1/u34.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ed944f603d26453690e66ffa62bbeef0",
              "label":"item4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6f7dc51c002f48ee92dc574fe02a06b6",
                  "label":"",
                  "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                  "panelIndex":3,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":310},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4d6abba20654d58861ffc51d77aa126",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                      "panelIndex":3,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":310},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_1/u34.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"82576f2a180f4410a74c85640180bdce",
              "label":"item5",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a946de6a4ba64ae189415f2902006d90",
                  "label":"",
                  "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                  "panelIndex":4,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":310},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF009DDA},
                    "cornerRadiusTopLeft":"1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e2041008b9847db8ddd4547e70b82d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"85cfb5be25464ab79890ab257b3cd47d",
                      "panelIndex":4,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":310},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF009DDA},
                        "cornerRadiusTopLeft":"1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_1/u34.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d855388145d1495fa4e6cbda98f4ab7b",
          "label":"item1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DDA,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "fontWeight":"bold"}},
            "location":{
              "x":-10,
              "y":41},
            "size":{
              "width":221,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f2970d968b04ff686e3517fcec9227a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "fontWeight":"bold"}},
                "location":{
                  "x":-10,
                  "y":41},
                "size":{
                  "width":221,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 当前部件 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelOrder",
                      "description":"置 neirong 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelOrder",
                      "description":"置 当前部件 到顶层 ",
                      "panelPaths":[{
                          "panelPath":["d855388145d1495fa4e6cbda98f4ab7b"],
                          "setOrderInfo":{
                            "bringToFront":true}}]},
{
                      "action":"setPanelState",
                      "description":"设置 neirong 到 [[this.name]]",
                      "panelsToStates":[{
                          "panelPath":["85cfb5be25464ab79890ab257b3cd47d"],
                          "stateInfo":{
                            "setStateType":"value",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"[[this.name]]",
                              "stos":[{
                                  "computedType":"string",
                                  "sto":"propCall",
                                  "thisSTO":{
                                    "desiredType":"widget",
                                    "sto":"var",
                                    "name":"this"},
                                  "prop":"name"}]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/page_1/item2_u21.png",
            "selected~":"images/page_1/item2_u21.png"}}]}},
  "masters":{
    "db990852ebc84abf82832ff2cb120105":{
      "packageId":"db990852ebc84abf82832ff2cb120105",
      "type":"Axure:Master",
      "name":"head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa1d19b1f069426fb269f6d3f8e524a6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":1200,
                "height":40},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xCC797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"039e19464acb4df3a25a8a63c513f771",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":1200,
                    "height":40},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xCC797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u2.png"}},
{
            "id":"f4cd25e2731c4227b696a6ca554e298b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF33CC00},
              "location":{
                "x":1015,
                "y":5},
              "size":{
                "width":30,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"12"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c214ffb6eab74cdf9276426a5e3b55e5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF33CC00},
                  "location":{
                    "x":1015,
                    "y":5},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"12"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u4.png"}},
{
            "id":"26ed30c789d44e428528843524078bbe",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":150,
                "y":12},
              "size":{
                "width":60,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"564db863b9604652a0f1698e87842baf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":150,
                    "y":12},
                  "size":{
                    "width":60,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6114b71d8649402db5ddf869a7c984ac",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":250,
                "y":12},
              "size":{
                "width":60,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"17d6f8b79faa4c0abf17ea54e4c58b1e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":250,
                    "y":12},
                  "size":{
                    "width":60,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"21ec22c439b7423384e4196d05fb1915",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":340,
                "y":12},
              "size":{
                "width":60,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d62ae31e0c69484089ffe1d2900d7648",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":340,
                    "y":12},
                  "size":{
                    "width":60,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7a7e545d39e04c788b4612d678da081d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1150,
                "y":12},
              "size":{
                "width":40,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c1360a10764143d790e94ac037d7e109",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1150,
                    "y":12},
                  "size":{
                    "width":40,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"32fd2e70e2df430699632bb318252395",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1055,
                "y":12},
              "size":{
                "width":85,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"10ce99112dbc401baa0df17533ea8234",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1055,
                    "y":12},
                  "size":{
                    "width":85,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1fb81ac73fbe413491f42c9a104de143",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":1017,
                "y":8},
              "size":{
                "width":25,
                "height":25},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7d54b9fb0c794acbbd39bf5c623cd4ab",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":1017,
                    "y":8},
                  "size":{
                    "width":25,
                    "height":25},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u16.png"}},
{
            "id":"936b7f0b9b454f5dbdb2f20f90d8735b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":1032,
                "y":4},
              "size":{
                "width":14,
                "height":11}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e6cc91f702d9414493c707a8a0c342fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":1032,
                    "y":4},
                  "size":{
                    "width":14,
                    "height":11}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"85b836b752e346d7bb387681b2af797b",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":60,
                "y":12},
              "size":{
                "width":60,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"457ec698f02148648e0281e7a056c886",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":60,
                    "y":12},
                  "size":{
                    "width":60,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 Home",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "02e594a5cb8e46848360667a5ad5302e":{
      "scriptId":"u0",
      "aa1d19b1f069426fb269f6d3f8e524a6":{
        "scriptId":"u1"},
      "039e19464acb4df3a25a8a63c513f771":{
        "scriptId":"u2"},
      "f4cd25e2731c4227b696a6ca554e298b":{
        "scriptId":"u3"},
      "c214ffb6eab74cdf9276426a5e3b55e5":{
        "scriptId":"u4"},
      "26ed30c789d44e428528843524078bbe":{
        "scriptId":"u5"},
      "564db863b9604652a0f1698e87842baf":{
        "scriptId":"u6"},
      "6114b71d8649402db5ddf869a7c984ac":{
        "scriptId":"u7"},
      "17d6f8b79faa4c0abf17ea54e4c58b1e":{
        "scriptId":"u8"},
      "21ec22c439b7423384e4196d05fb1915":{
        "scriptId":"u9"},
      "d62ae31e0c69484089ffe1d2900d7648":{
        "scriptId":"u10"},
      "7a7e545d39e04c788b4612d678da081d":{
        "scriptId":"u11"},
      "c1360a10764143d790e94ac037d7e109":{
        "scriptId":"u12"},
      "32fd2e70e2df430699632bb318252395":{
        "scriptId":"u13"},
      "10ce99112dbc401baa0df17533ea8234":{
        "scriptId":"u14"},
      "1fb81ac73fbe413491f42c9a104de143":{
        "scriptId":"u15"},
      "7d54b9fb0c794acbbd39bf5c623cd4ab":{
        "scriptId":"u16"},
      "936b7f0b9b454f5dbdb2f20f90d8735b":{
        "scriptId":"u17"},
      "e6cc91f702d9414493c707a8a0c342fd":{
        "scriptId":"u18"},
      "85b836b752e346d7bb387681b2af797b":{
        "scriptId":"u19"},
      "457ec698f02148648e0281e7a056c886":{
        "scriptId":"u20"}},
    "0418d3d12fed4d1e89501050544353e7":{
      "scriptId":"u21"},
    "ba47ac95f9234461800a2bfbcd3cc908":{
      "scriptId":"u22"},
    "f22fa59de9124552b25335a4fb854f41":{
      "scriptId":"u23"},
    "40644d3cdcb34e7eaa2e04d7e3dd28bf":{
      "scriptId":"u24"},
    "09f465a745ff4c4c97ef252a37d6a9cf":{
      "scriptId":"u25"},
    "4e27408f07ec4a7d8a904d292207f21e":{
      "scriptId":"u26"},
    "e19057d1febe4f61a7cf94c46b043ca2":{
      "scriptId":"u27"},
    "fe399e91dc6a4ae3903c262a380f90a4":{
      "scriptId":"u28"},
    "85cfb5be25464ab79890ab257b3cd47d":{
      "scriptId":"u29"},
    "0ffaba7204d8438880111befad12e664":{
      "scriptId":"u30"},
    "293856866c194b30ab8de9f4b0887ffb":{
      "scriptId":"u31"},
    "dac9d943d26146879ec76622b722c223":{
      "scriptId":"u32"},
    "c88e983b329d4acf93a98a99c5fa763c":{
      "scriptId":"u33"},
    "32a2a2f7e3f34e8484074b911ca73d50":{
      "scriptId":"u34"},
    "7f0d3d0d9da7427396f54d8e22856629":{
      "scriptId":"u35"},
    "6192acda93764b29b791150fccc08e5a":{
      "scriptId":"u36"},
    "7edb88f027904639b7f80bfed05cecd0":{
      "scriptId":"u37"},
    "6f7dc51c002f48ee92dc574fe02a06b6":{
      "scriptId":"u38"},
    "c4d6abba20654d58861ffc51d77aa126":{
      "scriptId":"u39"},
    "a946de6a4ba64ae189415f2902006d90":{
      "scriptId":"u40"},
    "2e2041008b9847db8ddd4547e70b82d3":{
      "scriptId":"u41"},
    "d855388145d1495fa4e6cbda98f4ab7b":{
      "scriptId":"u42"},
    "2f2970d968b04ff686e3517fcec9227a":{
      "scriptId":"u43"}}});